# swear_words_all = ['niger', 'nigg','nyga','nyger', 'cfel', 'cwel', 'cipa', 'twoja stara', 'twój stary', 'twoj stary', 'pirdol', 'pjeb', 'peniz', 'pieprz', 'dziwk', 'dzifk', 'szmat', 'pizd', 'chuj', 'dojeb',
# 'dopierdal', 'dopierdol', 'dup', 'huj', 'jeba', 'jebi', 'koorw', 'kórw', 'kurestwo',
# 'kurew', 'kurv', 'kurw', 'kurewski', 'kutas', 'matkojeb', 'nabarłożyć', 'najebać', 'najebac', 'najebał', 'najebal', 'najebała', 'najebala', 'najebane', 'najebany', 'najebaną', 'najebana', 'najebie', 'najebią', 'najebia', 'naopierdalać',
# 'naopierdalac', 'naopierdalał', 'naopierdalal', 'naopierdalała',
# 'naopierdalala', 'naopierdalała', 'napierdalać', 'napierdalac',
# 'napierdalający', 'napierdalajacy', 'napierdolić', 'napierdolic',
# 'nawpierdalać', 'nawpierdalac', 'nawpierdalał', 'nawpierdalal',
# 'nawpierdalała', 'nawpierdalala', 'obsrywać', 'obsrywac', 'obsrywający',
# 'obsrywajacy', 'odpieprzać', 'odpieprzac', 'odpieprzy', 'odpieprzył',
# 'odpieprzyl', 'odpieprzyła', 'odpieprzyla', 'odpierdalać',
# 'odpierdalac', 'odpierdol', 'odpierdolił', 'odpierdolil',
# 'odpierdoliła', 'odpierdolila', 'odpierdoli', 'odpierdalający',
# 'odpierdalajacy', 'odpierdalająca', 'odpierdalajaca', 'odpierdolić',
# 'odpierdolic', 'odpierdoli', 'odpierdolił', 'opieprzający',
# 'opierdalać', 'opierdalac', 'opierdala', 'opierdalający',
# 'opierdalajacy', 'opierdol', 'opierdolić', 'opierdolic', 'opierdoli',
# 'opierdolą', 'opierdola', 'piczka', 'pieprznięty', 'pieprzniety',
# 'pieprzony', 'pierdel', 'pierdlu', 'pierdolą', 'pierdola', 'pierdolący',
# 'pierdolacy', 'pierdoląca', 'pierdolaca', 'pierdol', 'pierdole',
# 'pierdolenie', 'pierdoleniem', 'pierdoleniu', 'pierdolę', 'pierdolec',
# 'pierdola', 'pierdolą', 'pierdolić', 'pierdolicie', 'pierdolic',
# 'pierdolił', 'pierdolil', 'pierdoliła', 'pierdolila', 'pierdoli',
# 'pierdolnięty', 'pierdolniety', 'pierdolisz', 'pierdolnąć',
# 'pierdolnac', 'pierdolnął', 'pierdolnal', 'pierdolnęła', 'pierdolnela',
# 'pierdolnie', 'pierdolnięty', 'pierdolnij', 'pierdolnik', 'pierdolona',
# 'pierdolone', 'pierdolony', 'pierdołki', 'pierdzący', 'pierdzieć',
# 'pierdziec', 'pizda', 'pizdą', 'pizde', 'pizdę', 'piździe', 'pizdzie',
# 'pizdnąć', 'pizdnac', 'pizdu', 'podpierdalać', 'podpierdalac',
# 'podpierdala', 'podpierdalający', 'podpierdalajacy', 'podpierdolić',
# 'podpierdolic', 'podpierdoli', 'pojeb', 'pojeba', 'pojebami',
# 'pojebani', 'pojebanego', 'pojebanemu', 'pojebani', 'pojebany',
# 'pojebanych', 'pojebanym', 'pojebanymi', 'pojebem', 'pojebać',
# 'pojebac', 'pojebalo', 'popierdala', 'popierdalac', 'popierdalać',
# 'popierdolić', 'popierdolic', 'popierdoli', 'popierdolonego',
# 'popierdolonemu', 'popierdolonym', 'popierdolone', 'popierdoleni',
# 'popierdolony', 'porozpierdalać', 'porozpierdala', 'porozpierdalac',
# 'poruchac', 'poruchać', 'przejebać', 'przejebane', 'przejebac',
# 'przyjebali', 'przepierdalać', 'przepierdalac', 'przepierdala',
# 'przepierdalający', 'przepierdalajacy', 'przepierdalająca',
# 'przepierdalajaca', 'przepierdolić', 'przepierdolic', 'przyjebać',
# 'przyjebac', 'przyjebie', 'przyjebała', 'przyjebala', 'przyjebał',
# 'przyjebal', 'przypieprzać', 'przypieprzac', 'przypieprzający',
# 'przypieprzajacy', 'przypieprzająca', 'przypieprzajaca',
# 'przypierdalać', 'przypierdalac', 'przypierdala', 'przypierdoli',
# 'przypierdalający', 'przypierdalajacy', 'przypierdolić',
# 'przypierdolic', 'qrwa', 'rozjebać', 'rozjebac', 'rozjebie',
# 'rozjebała', 'rozjebią', 'rozpierdalać', 'rozpierdalac', 'rozpierdala',
# 'rozpierdolić', 'rozpierdolic', 'rozpierdole', 'rozpierdoli',
# 'rozpierducha', 'skurwić', 'skurwiel', 'skurwiela', 'skurwielem',
# 'skurwielu', 'skurwysyn', 'skurwysynów', 'skurwysynow', 'skurwysyna',
# 'skurwysynem', 'skurwysynu', 'skurwysyny', 'skurwysyński',
# 'skurwysynski', 'skurwysyństwo', 'skurwysynstwo', 'spieprzać',
# 'spieprzac', 'spieprza', 'spieprzaj', 'spieprzajcie', 'spieprzają',
# 'spieprzaja', 'spieprzający', 'spieprzajacy', 'spieprzająca',
# 'spieprzajaca', 'spierdalać', 'spierdalac', 'spierdala', 'spierdalał',
# 'spierdalała', 'spierdalal', 'spierdalalcie', 'spierdalala',
# 'spierdalający', 'spierdalajacy', 'spierdolić', 'spierdolic',
# 'spierdoli', 'spierdoliła', 'spierdoliło', 'spierdolą', 'spierdola',
# 'srać', 'srac', 'srający', 'srajacy', 'srając', 'srajac', 'sraj',
# 'sukinsyn', 'sukinsyny', 'sukinsynom', 'sukinsynowi', 'sukinsynów',
# 'sukinsynow', 'śmierdziel', 'udupić', 'ujebać', 'ujebac', 'ujebał',
# 'ujebal', 'ujebana', 'ujebany', 'ujebie', 'ujebała', 'ujebala',
# 'upierdalać', 'upierdalac', 'upierdala', 'upierdoli', 'upierdolić',
# 'upierdolic', 'upierdoli', 'upierdolą', 'upierdola', 'upierdoleni',
# 'wjeb', 'wkurwiać', 'wkurwiac', 'wkurwi', 'wkurwia', 'wkurwiał',
# 'wkurwial', 'wkurwiający', 'wkurwiajacy', 'wkurwiająca', 'wkurwiajaca',
# 'wkurwić', 'wkurwic', 'wkurwi', 'wkurwiacie', 'wkurwiają', 'wkurwiali',
# 'wkurwią', 'wkurwia', 'wkurwimy', 'wkurwicie', 'wkurwiacie', 'wkurwić',
# 'wkurwic', 'wkurwia', 'wpierdalać', 'wpierdalac', 'wpierdalający',
# 'wpierdalajacy', 'wpierdol', 'wpierdolić', 'wpierdolic', 'wpizdu',
# 'wyjebać', 'wyjebac', 'wyjebali', 'wyjebał', 'wyjebac', 'wyjebała',
# 'wyjebały', 'wyjebie', 'wyjebią', 'wyjebia', 'wyjebiesz', 'wyjebie',
# 'wyjebiecie', 'wyjebiemy', 'wypieprzać', 'wypieprzac', 'wypieprza',
# 'wypieprzał', 'wypieprzal', 'wypieprzała', 'wypieprzala', 'wypieprzy',
# 'wypieprzyła', 'wypieprzyla', 'wypieprzył', 'wypieprzyl', 'wypierdal',
# 'wypierdalać', 'wypierdalac', 'wypierdala', 'wypierdalaj',
# 'wypierdalał', 'wypierdalal', 'wypierdalała', 'wypierdalala',
# 'wypierdalać', 'wypierdolić', 'wypierdolic', 'wypierdoli',
# 'wypierdolimy', 'wypierdolicie', 'wypierdolą', 'wypierdola',
# 'wypierdolili', 'wypierdolił', 'wypierdolil', 'wypierdoliła',
# 'wypierdolila', 'zajebać', 'zajebac', 'zajebie', 'zajebią', 'zajebia',
# 'zajebiał', 'zajebial', 'zajebała', 'zajebiala', 'zajebali', 'zajebana',
# 'zajebani', 'zajebane', 'zajebany', 'zajebanych', 'zajebanym',
# 'zajebanymi', 'zajebiste', 'zajebisty', 'zajebistych', 'zajebista',
# 'zajebistym', 'zajebistymi', 'zajebiście', 'zajebiscie', 'zapieprzyć',
# 'zapieprzyc', 'zapieprzy', 'zapieprzył', 'zapieprzyl', 'zapieprzyła',
# 'zapieprzyla', 'zapieprzą', 'zapieprza', 'zapieprzy', 'zapieprzymy',
# 'zapieprzycie', 'zapieprzysz', 'zapierdala', 'zapierdalać',
# 'zapierdalac', 'zapierdalaja', 'zapierdalał', 'zapierdalaj',
# 'zapierdalajcie', 'zapierdalała', 'zapierdalala', 'zapierdalali',
# 'zapierdalający', 'zapierdalajacy', 'zapierdolić', 'zapierdolic',
# 'zapierdoli', 'zapierdolił', 'zapierdolil', 'zapierdoliła',
# 'zapierdolila', 'zapierdolą', 'zapierdola', 'zapierniczać',
# 'zapierniczający', 'zasrać', 'zasranym', 'zasrywać', 'zasrywający',
# 'zesrywać', 'zesrywający', 'zjeb']

swear_words = ['niger', 'nigg', 'nyga', 'nyger', 'pirdol', 'pierdol', 'chuj', 'huj', 'kurv', 'kurw', 'zjeb', 'zjba', 'zapierdol', 'zapirdoli', 'spierdol', 'spierdal', 'wpierdol', 'wypierd', 'wkurw', 'wkurv', 'przyjeb', 'przyjb', 'ujeb', 'ujban', 'qrw', 'skurw', 'skurv', 'pizd', 'opierd', 'opirdole', 'nawpierd', 'nawpird', 'matkojeb', 'dziwk', 'dzifk', 'dzfki', 'dzwki', 'kurew', 'kuref', 'kuresk', 'najeb', 'najeb', 'najbane', 'njebana', 'zajeb', 'zajbane', 'zajbalem', 'zajbałem', 'wkurw', 'wkurv', 'pizd', 'jeba', 'szmata', 'szmato', 'wyjeb', 'wyjbane', 'jebać', 'jebac', 'jeban', 'jbane']

symbols = ["'", "-", "[", "]", ",", ".", ":", "/", "^", "!", "`", "~", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "@", "#", "%", "&", "*", "(", ")", "_", "-", "+", "=", "|", "{", "}", "[", "]", ";", ":", "?", ">", "<", " "]